"""Golden tests against v1 scoring output — nightly/release only.

Reads the golden_v1_capture.json fixture (generated by
scripts/capture_v1_golden.py) and verifies that v2's scoring engine
produces matching results within tolerance.

This test is marked @pytest.mark.slow and does NOT run in CI by
default. Run with: pytest -m slow tests/test_scoring_golden_v1.py

The fixture must be generated before this test can run. If the file
is missing, the test is skipped gracefully.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

_FIXTURES = Path(__file__).parent / "fixtures"
_V1_CAPTURE = _FIXTURES / "golden_v1_capture.json"


@pytest.mark.slow
class TestGoldenV1:
    """Compare v2 scores against v1 captured output."""

    @pytest.fixture()
    def v1_data(self) -> dict:  # type: ignore[type-arg]
        if not _V1_CAPTURE.exists():
            pytest.skip(
                f"Golden v1 capture not found at {_V1_CAPTURE}. "
                "Run scripts/capture_v1_golden.py first."
            )
        with _V1_CAPTURE.open() as f:
            data: dict[str, object] = json.load(f)
            return data

    def test_fixture_loads(self, v1_data: dict) -> None:  # type: ignore[type-arg]
        """Verify the fixture has the expected structure."""
        assert "_meta" in v1_data
        assert "countries" in v1_data
        assert len(v1_data["countries"]) > 0

    def test_composite_count(self, v1_data: dict) -> None:  # type: ignore[type-arg]
        """v1 should have scored a reasonable number of countries."""
        countries = v1_data["countries"]
        scored = sum(1 for c in countries.values() if c["composite"] is not None)
        # v1 typically scores 100+ countries with composites
        assert scored > 50, f"Only {scored} countries have composites"
